import { Raleway, Roboto_Mono } from 'next/font/google'
import '../styles/globals.css'

const raleway = Raleway({ subsets: ['latin'] })
const robotoMono = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className} >
        <div className="font-swap">{children}</div>
      </body>
    </html>
  )
}
